apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app
  labels:
    app: python-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
      annotations:
        # Optional: annotation-based scrape (works only if Prometheus watch is configured)
        prometheus.io/scrape: "true"
        prometheus.io/port: "5000"
        prometheus.io/path: "/metrics"
    spec:
      containers:
        - name: python-app
          image: gauravpatil2555/python-app:latest    # <-- update
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
